project:
  type: website
  output-dir: docs

website:
  title: "プロセカ資訊"
  navbar:
    light: 
      background: info
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: lumen
      dark: [solar, theme-dark.scss]
    css: styles.css
    toc: true



