project:
  type: website
  output-dir: docs

website:
  title: "プロセカ資訊"
  navbar:
    background: info
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



