---
title: 生日／紀念日
catagories: [紀念]
format:
  html:
    toc: false
---

<!-- Control buttons -->
<div id="myBtnContainer">
  <button class="btn active" onclick="filterSelection('all')"> Show all</button>
  <button class="btn" onclick="filterSelection('vs')"> Virtual Singer</button>
  <button class="btn" onclick="filterSelection('ln')"> Leo/need</button>
  <button class="btn" onclick="filterSelection('mmj')"> MORE MORE JUMP!</button>
  <button class="btn" onclick="filterSelection('vbs')"> Vivid Bad SQUAD</button>
  <button class="btn" onclick="filterSelection('ws')">ワンダーランズ×ショウタイム</button>
  <button class="btn" onclick="filterSelection('25ji')">2
  5時、ナイトコードで。</button>
  
</div>

<!-- The filterable elements. Note that some have multiple class names (this can be used if they belong to multiple categories) -->
<div class="container">
  <div class="badge rounded-pill rounded-pill vs" style="background-color: #33CCBB;">初音ミク</div>
  <div class="badge rounded-pill vs" style="background-color: #FFCC11;">鏡音リン</div>
  <div class="badge rounded-pill vs" style="background-color: #FFEE11;">鏡音レン</div>
  <div class="badge rounded-pill vs" style="background-color: #FFBBCC;">巡音ルカ</div>
  <div class="badge rounded-pill vs" style="background-color: #DD4444;">MEIKO</div>
  <div class="badge rounded-pill vs" style="background-color: #3366CC;">KAITO</div>
  <div class="badge rounded-pill ln" style="background-color: #33AAEE;">星乃一歌</div>
  <div class="badge rounded-pill ln" style="background-color: #FFDD44;">天馬咲希</div>
  <div class="badge rounded-pill ln" style="background-color: #EE6666;">望月穗波</div>
  <div class="badge rounded-pill ln" style="background-color: #BBDD22;">日野森志步</div>
  <div class="badge rounded-pill mmj" style="background-color: #FFCCAA;">花里みのり</div>
  <div class="badge rounded-pill mmj" style="background-color: #99CCFF;">桐谷遙</div>
  <div class="badge rounded-pill mmj" style="background-color: #FFAACC;">桃井愛莉</div>
  <div class="badge rounded-pill mmj" style="background-color: #99EEDD;">日野森雫</div>
  <div class="badge rounded-pill vbs" style="background-color: #FF6699;">小豆沢こはね</div>
  <div class="badge rounded-pill vbs" style="background-color: #00BBDD;">白石杏</div>
  <div class="badge rounded-pill vbs" style="background-color: #FF7722;">東雲彰人</div>
  <div class="badge rounded-pill vbs" style="background-color: #0077DD;">青柳冬弥</div>
  <div class="badge rounded-pill ws" style="background-color: #FFBB00;">天馬司</div>
  <div class="badge rounded-pill ws" style="background-color: #FF66BB;">鳳えむ</div>
  <div class="badge rounded-pill ws" style="background-color: #33DD99;">草薙寧々</div>
  <div class="badge rounded-pill ws" style="background-color: #BB88EE;">神代類</div>
  <div class="badge rounded-pill 25ji" style="background-color: #BB6688;">宵崎奏</div>
  <div class="badge rounded-pill 25ji" style="background-color: #8888CC;">朝比奈まふゆ</div>
  <div class="badge rounded-pill 25ji" style="background-color: #CCAA88;">東雲絵名</div>
  <div class="badge rounded-pill 25ji" style="background-color: #DDAACC;">曉山瑞希</div>
</div>

<div id="1" class="list">
  <!-- list content -->
<div class="list-content">
  <!-- Tab links -->
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '1-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '1-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="1-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1425109692099956736?s=20&t=FjvxBzP26rIcl6O-jfegGg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
  <div id="1-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1557381266634334210?s=20&t=FjvxBzP26rIcl6O-jfegGg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>
</div>

<div id="2" class="list">
  <!--list content-->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '2-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '2-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="2-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1391045234683899908?s=20&t=pc98bmsbEYqHu3OrUWN7iQ"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
  <div id="2-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1523316799802073088?s=20&t=pc98bmsbEYqHu3OrUWN7iQ"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>
</div>

<div id="3" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '3-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '3-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '3-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="3-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1320745584039321600?s=20&t=46GHhKJt91F-syZe3xS9Ag"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="3-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1453013560905240576?s=20&t=46GHhKJt91F-syZe3xS9Ag"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="3-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1585285120348520448?s=20&t=46GHhKJt91F-syZe3xS9Ag"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>  
  </div>
</div>
</div>

<div id="4" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '4-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '4-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="4-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1347196321246035970?s=20&t=46GHhKJt91F-syZe3xS9Ag"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="4-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1479467868853084161?s=20&t=46GHhKJt91F-syZe3xS9Ag"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="5" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '5-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '5-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="5-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1382166735772475395?s=20&t=soGoTqrO4mll1nfF3AMjCA"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="5-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1514257120694190087?s=20&t=soGoTqrO4mll1nfF3AMjCA"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="6" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '6-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '6-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '6-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="6-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1312769448642637825?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="6-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1445041030559113227?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="6-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1577312593248538626?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="7" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '7-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '7-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="7-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1372563466863529987?s= 20&t=soGoTqrO4mll1nfF3AMjCA"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="7-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1504835020363546654?s=20&t=soGoTqrO4mll1nfF3AMjCA"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="8" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '8-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '8-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '8-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="8-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1335237518887854087?s=20&t=Ove7ynFGvwuga8cN98d09g"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="8-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1467509073444704261?s=20&t=soGoTqrO4mll1nfF3AMjCA"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="8-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1599780641364529152?s=20&t=soGoTqrO4mll1nfF3AMjCA"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="9" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '9-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '9-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="9-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1366402936100712450?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="9-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1498674430603677702?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="10" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '10-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '10-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="10-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1419311485327601669?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="10-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1551583054497345537?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="11" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '11-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '11-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '11-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="11-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1326540206439161859?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="11-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1458811756751450121?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="11-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1591083336742719490?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="12" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '12-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '12-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="12-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1396843429624156168?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="12-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1529115013805375489?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="13" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '13-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '13-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="13-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1393944335540920320?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="13-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1526215904727642112?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="14" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '14-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '14-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="14-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1435618939225219074?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="14-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1567890644684705794?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="15" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '15-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '15-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="15-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1417137160147415048?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="15-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1549408734312554502?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="16" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '16-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '16-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="16-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1407715065487192073?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="16-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1539986641070301184?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="17" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '17-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '17-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="17-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1359155161906708483?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="17-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1491426665309765635?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="18" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '18-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '18-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="18-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1354081660950687744?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="18-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1486353241327783942?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="19" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '19-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '19-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="19-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1387783734665965568?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="19-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1520055317249204225?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="20" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '20-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '20-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="20-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1430907897748221962?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="20-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1563179475570868227?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="21" class="list">
  <!-- list content -->
<div class="list-content">
<div class="tab">
  <button class="tablinks" onclick="openYear(event, '21-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '21-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '21-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="21-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1300085927725817859?s=20&t=7PXo4w5VbeejuTSmB_WsYA"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="21-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1432357453367111688?s=20&t=h_gLhcKloVaBl_HFZ9qAcg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="21-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1564629022369165316?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="22" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '22-2019')">2019</button>
  <button class="tablinks" onclick="openYear(event, '22-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '22-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '22-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="22-2019" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1210395219809558528?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="22-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1342847672550522882?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="22-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1475119209931759623?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="22-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1607390907342508034?s=20&t=ELL1cR35eavgFMk8nCoKJQ"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="23" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '23-2019')">2019</button>
  <button class="tablinks" onclick="openYear(event, '23-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '23-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '23-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="23-2019" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1210395219809558528?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="23-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1342847672550522882?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="23-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1475119209931759623?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="23-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1607390907342508034?s=20&t=ELL1cR35eavgFMk8nCoKJQ"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="24" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '24-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '24-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '24-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="24-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1222535206571139073?s=20&t=Nuab3zVId4iie6eokLOPQgg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="24-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1355168826141384704?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="24-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1487440401476771842?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="25" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '25-2019')">2019</button>
  <button class="tablinks" onclick="openYear(event, '25-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '25-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '25-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="25-2019" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1191369678582472706?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="25-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1324003601073627137?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="25-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1456275051863429132?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="25-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1588546619712094209?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>

<div id="26" class="list">
  <!-- list content -->
<div class="list-content">
  <div class="tab">
  <button class="tablinks" onclick="openYear(event, '26-2020')">2020</button>
  <button class="tablinks" onclick="openYear(event, '26-2021')">2021</button>
  <button class="tablinks" onclick="openYear(event, '26-2022')">2022</button>
  </div>
  <!-- Tab content -->
  <div id="26-2020" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1229057983381823489?s=20&t=3zKQf5WnhPfPskVnaCflHw"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="26-2021" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1361691844212494337?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
  <div id="26-2022" class="tabcontent">
  <blockquote class="twitter-tweet" style="height:50px"><a href="https://twitter.com/pj_sekai/status/1493963380478156803?s=20&t=Nuab3zVId4iie6eokLOPQg"></a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>
</div>
</div>


<style>

.container {
  overflow: hidden;
}

.badge {
  float: left;
  color: #000000;
  width: 110px;
  line-height: 30px;
  font-size:12px;
  text-align: center;
  margin: 3px;
  display: none; /* Hidden by default */
  cursor: pointer;
}

.badge:hover{
  filter: drop-shadow(2px 2px 2px darkgrey);
}

.badge.chara-active{
  filter: drop-shadow(0px 0px 3px darkgrey);
  -webkit-box-shadow:inset 0px 0px 0px 2px #888;
  -moz-box-shadow:inset 0px 0px 0px 2px #888;
  box-shadow:inset 0px 0px 0px 2px #f1f1f1;
}

/* The "show" class is added to the filtered elements */
.show {
  display: block;
}

/* Style the buttons */
.btn {
  border: none;
  border-radius: 5px;
  outline: none;
  padding: 8px 12px;
  margin: 4px 2px;
  background-color: #f1f1f1;
  cursor: pointer;
}

/* Add a light grey background on mouse-over */
.btn:hover {
  background-color: #ddd;
}

/* Add a dark background to the active button */
.btn.active {
  background-color: #666;
  color: white;
}

.list {
  display: none; /* Hidden by default */
  /*position: fixed; /* Stay in place */
  /*z-index: 1; /* Sit on top */
  /*left: 0;
  top: 0;
  width: 100%; /* Full width */
  /*height: 100%; /* Full height */
 /*overflow: auto; /* Enable scroll if needed */
  /*background-color: rgb(0,0,0); /* Fallback color */
  /*background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* list Content Box */
.list-content {
  background-color: #fefefe;
  margin: 0% auto; /* 15% from the top and centered */
  padding-top: 20px;
  /*border: 1px solid #888;*/
  width: 100%; /* Could be more or less, depending on screen size */
  -webkit-animation-name: animatetop;
  -webkit-animation-duration: 0.4s; 
}

/* Add Animation */
@-webkit-keyframes animatetop {
  from {top:-300px; opacity:0} 
  to {top:0; opacity:1}
}

@keyframes animatetop {
  from {top:-300px; opacity:0}
  to {top:0; opacity:1}
}

/* Style the tab */
.tab {
  overflow: hidden;
  /*border: 1px solid #ccc;*/
  background-color: #f1f1f1;
}

/* Style the buttons that are used to open the tab content */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
}

.twitter-tweet {
  margin-left:auto;
  margin-right:auto;
}


</style>

<script>

filterSelection("all");




function filterSelection(c) {
  var x, i;
  x = document.querySelectorAll('.badge');
  var lists = document.querySelectorAll('.list');

  if (c == "all") c = "";
  // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
  for (i = 0; i < x.length; i++) {
    RemoveClass(x[i], "show");
    if (x[i].className.indexOf(c) > -1) AddClass(x[i], "show");
  }

  x[0].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[20].style.display = "block"; 
    AddClass(x[0], "chara-active");
  };
  x[1].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[21].style.display = "block"; 
    AddClass(x[1], "chara-active");
    };
  x[2].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[22].style.display = "block";
    AddClass(x[2], "chara-active");
  };
  x[3].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[23].style.display = "block"; 
    AddClass(x[3], "chara-active");
  };
  x[4].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[24].style.display = "block"; 
    AddClass(x[4], "chara-active");
  };
  x[5].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[25].style.display = "block"; 
    AddClass(x[5], "chara-active");
  };
  x[6].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[0].style.display = "block"; 
    AddClass(x[6], "chara-active");
  };
  x[7].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[1].style.display = "block"; 
    AddClass(x[7], "chara-active");
  }
  x[8].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[2].style.display = "block"; 
    AddClass(x[8], "chara-active");
  };
  x[9].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[3].style.display = "block"; 
    AddClass(x[9], "chara-active");
  };
  x[10].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[4].style.display = "block"; 
    AddClass(x[10], "chara-active");
  };
  x[11].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[5].style.display = "block"; 
    AddClass(x[11], "chara-active");
  };
  x[12].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[6].style.display = "block"; 
    AddClass(x[12], "chara-active");
  };
  x[13].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[7].style.display = "block"; 
    AddClass(x[13], "chara-active");
  };
  x[14].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[8].style.display = "block"; 
    AddClass(x[14], "chara-active");
  };
  x[15].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[9].style.display = "block"; 
    AddClass(x[15], "chara-active");
  };
  x[16].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[10].style.display = "block"; 
    AddClass(x[16], "chara-active");
  };
  x[17].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[11].style.display = "block"; 
    AddClass(x[17], "chara-active");
  };
  x[18].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[12].style.display = "block"; 
    AddClass(x[18], "chara-active");
  };
  x[19].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[13].style.display = "block"; 
    AddClass(x[19], "chara-active");
  };
  x[20].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[14].style.display = "block"; 
    AddClass(x[20], "chara-active");
  };
  x[21].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[15].style.display = "block"; 
    AddClass(x[21], "chara-active");
  };
  x[22].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[16].style.display = "block"; 
    AddClass(x[22], "chara-active");
  };
  x[23].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[17].style.display = "block"; 
    AddClass(x[23], "chara-active");
  };
  x[24].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[18].style.display = "block"; 
    AddClass(x[24], "chara-active");
  };
  x[25].onclick = function() {
    for (i = 0; i < lists.length; i++) {
      lists[i].style.display = "none";
      RemoveClass(x[i], "chara-active");
    };
    lists[19].style.display = "block"; 
    AddClass(x[25], "chara-active");
  };
}



// Show filtered elements
function AddClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) == -1) {
      element.className += " " + arr2[i];
    }
  }
}

// Hide elements that are not selected
function RemoveClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    while (arr1.indexOf(arr2[i]) > -1) {
      arr1.splice(arr1.indexOf(arr2[i]), 1);
    }
  }
  element.className = arr1.join(" ");
}

// Add active class to the current control button (highlight it)
var btnContainer = document.getElementById("myBtnContainer");
var btns = btnContainer.getElementsByClassName("btn");
for (var i = 0; i < btns.length; i++) {
  btns[i].addEventListener("click", function() {
    var current = document.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    this.className += " active";
  });
}

function openYear(evt, year) {
  // Declare all variables
  var i, tabcontent, tablinks;

  // Get all elements with class="tabcontent" and hide them
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  // Get all elements with class="tablinks" and remove the class "active"
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  // Show the current tab, and add an "active" class to the button that opened the tab
  document.getElementById(year).style.display = "block";
  evt.currentTarget.className += " active";
}

</script>